AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Epsagon Logs Sender'
Parameters:
  EpsagonLogsKinesis:
    Type: String
Resources:
  EpsagonLogsSender:
    Properties:
      CodeUri: s3://epsagon-logs-sender/cloudwatch_log_sender.zip
      Environment:
        Variables:
          EPSAGON_KINESIS:
            Ref: EpsagonLogsKinesis
      Handler: cloudwatch_log_sender.handler
      MemorySize: 128
      Runtime: python3.6
      Timeout: 60
      Policies:
       - AWSLambdaExecute # Managed Policy
       - Version: '2012-10-17' # Policy Document
         Statement:
           - Effect: Allow
             Action:
               - logs:CreateLogStream
               - logs:PutLogEvents
             Resource: 'arn:aws:logs:*:*:log-group:*:*'
           - Effect: Allow
             Action:
               - logs:CreateLogStream
               - logs:PutLogEvents
             Resource: 'arn:aws:logs:us-*:*:*'
    Type: AWS::Serverless::Function